# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='run_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggeredby_set', to='scripts.Script', verbose_name='Run script'),
        ),
    ]
