# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField(blank=True, null=True, verbose_name='PID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Queued'), (2, 'Running'), (3, 'Executed'), (4, 'Canceled')], default=1, verbose_name='Status')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Host', verbose_name='Target Host')),
                ('network_addres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.NetworkAdress', verbose_name='Target Host')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script', verbose_name='Executed Script')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scripts.Trigger', verbose_name='Triggered by')),
            ],
            options={
                'verbose_name': 'Host Inspection',
                'verbose_name_plural': 'Host Inspections',
            },
        ),
        migrations.CreateModel(
            name='InspectionVulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('extended_data', models.TextField(verbose_name='Extended Data')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Inspection', verbose_name='Inspection')),
                ('vulnerability_detected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Vulnerability', verbose_name='Vulnerability Detected')),
            ],
            options={
                'verbose_name': 'Vulnerability detected by inspection',
                'verbose_name_plural': 'Vulnerabilities detectedd by inspection',
            },
        ),
    ]
